version: '3.1'

services:
  composer:
    build:
      context: .docker/php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
        - .:/var/www/symfony
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_ENV: prod
    command:
      - /bin/bash
      - -c
      - |
        /usr/bin/composer install --no-dev --optimize-autoloader
  node:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        yarn install
        yarn encore production
    depends_on:
      composer:
        condition: service_completed_successfully
