version: '3.1'

services:
  web:
    image: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/symfony
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
      - mysql
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: lyac
      MYSQL_DATABASE: lyac
  php:
    build:
      context: .docker/php7-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
        - .:/var/www/symfony
  node:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npx sb upgrade
        yarn encore dev
