controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        lt: ''
        en: '/en'
        pl: '/pl'
        uk: '/uk'
rules:
    path: /{_locale}/rules
    controller: App\Controller\RulesController::index
    requirements:
        _locale: en|lt|pl|uk